parameters:
    xls.phpexcel.class: PHPExcel
    xls.stream_writer.class: n3b\Bundle\Util\HttpFoundation\StreamResponse\StreamWriterWrapper
    xls.stream_response.class: n3b\Bundle\Util\HttpFoundation\StreamResponse\StreamResponse
    xls.factory.class: "PHPExcel_IOFactory"
    xls.factory.method: "createWriter"
    xls.factory.write_method: "save"
    xls.service.class: liuggio\ExcelBundle\Service\ExcelContainer

services:
    xls.phpexcel:
        class: %xls.phpexcel.class%
    xls.factory_xls5:
        class: %xls.factory.class%       
        arguments: [@xls.phpexcel, "Excel5"]
    xls.stream_writer_output:
        class: %xls.stream_writer.class%
        argument: "php://output"
    xls.service_xls5:
        class: %xls.service.class%
        arguments: [@xls.phpexcel, %xls.factory.class%, %xls.factory.method%, %xls.factory.write_method%, @xls.stream_writer_output, "Excel5", %xls.stream_response.class%]

